function(target_tests LEVEL_PREFIX)
    file(GLOB_RECURSE TEST_SOURCES "${CMAKE_CURRENT_LIST_DIR}/${LEVEL_PREFIX}_*/test_*.cpp")
    foreach(S ${TEST_SOURCES})
        get_filename_component(T ${S} NAME_WE)
        add_executable(${T} ${S})
		get_target_property(CXX_STANDARD_VERSION ${SCLP_LIBRARY_NAME} CXX_STANDARD)
        set_target_properties(${T} PROPERTIES CXX_STANDARD ${CXX_STANDARD_VERSION})
        target_link_libraries(${T} PRIVATE GTest::gtest GTest::gtest_main ${SCLP_LIBRARY_NAME})
        gtest_discover_tests(${T})
    endforeach()
endfunction()
